// Even Fibonacci numbers
/*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include<bits/stdc++.h>
using namespace std;

long int sumofEvenFibonacci(long int a){
    if(a == 1 || a == 0){
        return 1;
    }
    else{
        return sumofEvenFibonacci(a -1) + sumofEvenFibonacci(a -2);
    }
}

long int Method2(long int a){
    long int b, c, d =0, sum = 0;    
    b = 0;
    c = 1;
    while(d <= a){
        d = b+c;
        if(d%2 == 0){
            sum += d;
        }
        b = c;
        c = d;
    }
    return sum;
}

int main(){    
    long int num, i =0, sum =0;
    bool flag =true;
    while(flag){
        num = sumofEvenFibonacci(i);
        if(num <= 4000000){
            if(num%2 == 0){
                sum+= num;
            }
        }
        else{
            flag = false;
        }
        i++;
    }
    cout << sum << endl;

    cout << Method2(4000000) << endl;

}